# Generated by Django 3.2.8 on 2021-10-30 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_app_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
